spring:
  application:
    name: customer

  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5400/customer
    password: 'password'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQlDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'

